-- users, devices, alarms.
--
-- Conventions for every syncable table (all later migrations follow them):
--   id          uuid PK, generated by the client (offline-first inserts, idempotent retries)
--   user_id     Clerk user id (text, = auth.jwt()->>'sub'); FK to users, ON DELETE CASCADE
--   device_id   writing device (not an FK: pushes may arrive before the device row)
--   created_at / updated_at / version  -- updated_at + version are server-managed (sync_touch trigger)
--   deleted_at  soft-delete tombstone so other devices learn about deletions
-- Child tables reference parents with composite (parent_id, user_id) FKs so a row can never point
-- at another user's parent (RI checks bypass RLS, so this has to be structural). FKs are DEFERRABLE
-- INITIALLY DEFERRED so a batch can push parents and children in one transaction in any order.

create table public.users (
  id         text primary key check (length(id) between 1 and 255),   -- Clerk user id
  timezone   text,                                                    -- last known IANA zone
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger users_set_updated_at before update on public.users
  for each row execute function public.set_updated_at();

create table public.devices (
  id           uuid primary key,
  user_id      text not null references public.users (id) on delete cascade,
  device_id    uuid not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  version      bigint not null default 1,
  deleted_at   timestamptz,
  platform     text not null check (platform in ('ios', 'android')),
  os_version   text,
  app_version  text,
  device_model text,
  timezone     text,
  alarm_engine text not null default 'native' check (alarm_engine in ('native', 'preview')),
  readiness    jsonb not null default '{}' check (jsonb_typeof(readiness) = 'object'),  -- last diagnostics snapshot
  last_seen_at timestamptz
);

-- Alarm schedule is folded into this table instead of a separate alarm_schedules table: D9 gives
-- every alarm exactly one wall-clock rule (hour/minute + weekdays or one-time date), so a 1:1 child
-- would only add a join and a second tombstone/version to keep in step. Concrete fire instants live
-- in alarm_occurrences. If multi-rule alarms ever ship, split the schedule columns out then.
create table public.alarms (
  id                     uuid primary key,
  user_id                text not null references public.users (id) on delete cascade,
  device_id              uuid not null,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  version                bigint not null default 1,
  deleted_at             timestamptz,
  label                  text not null default '' check (length(label) <= 100),
  enabled                boolean not null default true,
  -- schedule (D9: wall-clock, evaluated on device)
  hour                   smallint not null check (hour between 0 and 23),
  minute                 smallint not null check (minute between 0 and 59),
  weekdays               smallint[] not null default '{}'
                           check (weekdays <@ array[1, 2, 3, 4, 5, 6, 7]::smallint[]),  -- ISO: 1 = Monday .. 7 = Sunday; empty = not weekly
  one_time_date          date,
  timezone_policy        text not null default 'floating' check (timezone_policy in ('floating', 'fixed')),
  timezone               text,
  skip_date              date,                                   -- "skip next occurrence"
  override_date          date,                                   -- temporary one-off time override
  override_hour          smallint check (override_hour between 0 and 23),
  override_minute        smallint check (override_minute between 0 and 59),
  -- ringing behaviour
  sound                  text,
  vibrate                boolean not null default true,
  gradual_volume         boolean not null default true,
  snooze_enabled         boolean not null default true,
  snooze_minutes         smallint not null default 5 check (snooze_minutes between 1 and 60),
  snooze_limit           smallint check (snooze_limit between 0 and 20),   -- null = unlimited
  -- anti-oversleep
  mission_chain          jsonb not null default '[]'
                           check (jsonb_typeof(mission_chain) = 'array' and jsonb_array_length(mission_chain) <= 5),  -- [{type, difficulty, ...}]
  mission_before_snooze  boolean not null default false,
  wake_check_enabled     boolean not null default false,
  wake_check_delay_minutes smallint not null default 5 check (wake_check_delay_minutes between 1 and 30),
  wake_check_method      text not null default 'confirm' check (wake_check_method in ('confirm', 'movement', 'mission')),
  constraint alarms_recurring_xor_one_time check (cardinality(weekdays) = 0 or one_time_date is null),
  constraint alarms_fixed_tz_needs_zone check (timezone_policy = 'floating' or timezone is not null),
  constraint alarms_override_complete check (
    (override_date is null and override_hour is null and override_minute is null)
    or (override_date is not null and override_hour is not null and override_minute is not null)
  ),
  unique (id, user_id)
);
